wandb_version: 1

I22_plot:
  desc: null
  value:
  - 8
  - 0
  - 1
  - 2
  - 8
  - 4
  - 5
  - 6
  - 8
  - 9
  - 10
  - 9
  - 12
  - 13
  - 14
  - 14
  - 9
  - 17
  - 18
  - 19
  - 19
Index127:
  desc: null
  value:
  - - 0
    - 1
  - - 2
    - 3
  - - 4
    - 5
  - - 6
    - 7
  - - 7
    - 8
  - - 9
    - 10
  - - 10
    - 11
Index2212:
  desc: null
  value:
  - - 0
  - - 1
    - 2
    - 3
  - - 4
  - - 5
    - 6
    - 7
  - - 8
    - 9
  - - 10
    - 11
  - - 12
  - - 13
  - - 14
    - 15
    - 16
  - - 17
  - - 18
  - - 19
    - 20
    - 21
Index74:
  desc: null
  value:
  - - 0
    - 2
  - - 1
    - 2
  - - 3
    - 4
  - - 5
    - 6
J22_plot:
  desc: null
  value:
  - 0
  - 1
  - 2
  - 3
  - 4
  - 5
  - 6
  - 7
  - 9
  - 10
  - 11
  - 12
  - 13
  - 14
  - 15
  - 16
  - 17
  - 18
  - 19
  - 20
  - 21
LR22_plot:
  desc: null
  value:
  - 0
  - 0
  - 0
  - 0
  - 1
  - 1
  - 1
  - 1
  - 0
  - 0
  - 0
  - 1
  - 1
  - 1
  - 1
  - 1
  - 0
  - 0
  - 0
  - 0
  - 0
_wandb:
  desc: null
  value:
    cli_version: 0.13.10
    code_path: code/main.py
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.10.9
    start_time: 1676365706.005018
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 13
      - 16
      - 23
      4: 3.10.9
      5: 0.13.10
      8:
      - 5
config:
  desc: null
  value: config/MSRGCN/h36m/demo.yaml
dct_n:
  desc: null
  value: 35
debug_step:
  desc: null
  value: 1
device:
  desc: null
  value: cuda:0
dim_repeat_22:
  desc: null
  value:
  - 9
  - 9
  - 14
  - 16
  - 19
  - 21
dim_repeat_32:
  desc: null
  value:
  - 16
  - 24
  - 20
  - 23
  - 28
  - 31
dim_used_3d:
  desc: null
  value:
  - 2
  - 3
  - 4
  - 5
  - 7
  - 8
  - 9
  - 10
  - 12
  - 13
  - 14
  - 15
  - 17
  - 18
  - 19
  - 21
  - 22
  - 25
  - 26
  - 27
  - 29
  - 30
exp_name:
  desc: null
  value: h36m
feeder:
  desc: null
  value: feeder.MSRGCN.datas.h36m.H36MMotionDataset
final_out_noden:
  desc: null
  value: 22
frame_ids:
  desc: null
  value:
  - 1
  - 3
  - 7
  - 9
  - 13
  - 24
input_n:
  desc: null
  value: 10
is_load:
  desc: null
  value: 0
is_train:
  desc: null
  value: 1
leaky_c:
  desc: null
  value: 0.2
lr:
  desc: null
  value: 0.0002
lr_decay:
  desc: null
  value: 0.98
model:
  desc: null
  value: models.MSRGCN.msrgcn.MSRGCN
modle_path:
  desc: null
  value: ''
n_epoch:
  desc: null
  value: 5000
num_workers:
  desc: null
  value: 1
num_works:
  desc: null
  value: 8
optimizer:
  desc: null
  value: torch.optim.Adam
origin_noden:
  desc: null
  value: 32
output_n:
  desc: null
  value: 25
p_dropout:
  desc: null
  value: 0.1
path_to_data:
  desc: null
  value: /share/zhangjinrong//human_motion_prediction/data/h3.6m/dataset
sample_rate:
  desc: null
  value: 2
seed:
  desc: null
  value: 3450
seq_len:
  desc: null
  value: 35
subs:
  desc: null
  value:
  - - 1
  - - 5
  - - 11
teat_split:
  desc: null
  value: 1
test_batch_size:
  desc: null
  value: 256
test_loss:
  desc: null
  value: losses.loss.L2NormLoss_test
test_manner:
  desc: null
  value: all
train_batch_size:
  desc: null
  value: 16
train_loss:
  desc: null
  value: losses.loss.L2NormLoss_train
train_manner:
  desc: null
  value: all
train_split:
  desc: null
  value: 0
validation_split:
  desc: null
  value: 2
visible_cuda:
  desc: null
  value: '1'
wandb_key:
  desc: null
  value: fbd8bd3a0f05a3323688c35c2cd5c5bc92a0f490
wandb_project:
  desc: null
  value: MSRGCN
work_dir:
  desc: null
  value: work_dir/MSRGCN/h36m/test1
