wandb_key: fbd8bd3a0f05a3323688c35c2cd5c5bc92a0f490
wandb_project: GISLR

work_dir: work_dir/GISLR/test # 结果保存路径

runner: runner.classfication_runner
is_load: 0
is_train: 1
# feeder
exp_name: gislr
feeder: feeder.GISLR.motiondataset.GislrDataset
path_to_data: /share/zhangjinrong//human_motion_prediction/data/h3.6m/dataset

debug_step: 1

# model
model: models.GISLR.test.Model

# optim
lr: 2e-4
lr_decay: 0.98
n_epoch: 60
leaky_c: 0.2 # 原版为0.2
optimizer: torch.optim.Adam
train_loss: torch.nn.CrossEntropyLoss
test_loss: torch.nn.CrossEntropyLoss

# train
# ml_weight: 0.3 # 这个是给zjr添加到原有二范数损失的measure度量损失中调整比例的超参，先给个1看一下
p_dropout: 0.1
train_batch_size: 16
test_batch_size: 256
input_n: 10
output_n: 25
seq_len: 35 # input_n + output_n
dct_n: 35 # 与sqe_len相同
frame_ids: [1, 3, 7, 9, 13, 24]

# test

# computer
visible_cuda: '0'
device: 'cuda:0'
num_workers: 1
seed: 3450 # 设置torch随机种子